#!/bin/bash

docker run -d \
           --rm \
           --name ovs-photon-0 \
           --net lightwave \
           --privileged \
           --hostname ovs-0.lightwave.local \
           --ip 192.168.114.6 \
           --dns 192.168.114.3 \
           --dns-search lightwave.local \
           -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
           --cap-add=SYS_PTRACE \
           --security-opt seccomp=unconfined \
           ovs/ovs-photon:1.0.0 /sbin/init
